"""added note model

Revision ID: 52338fcc6a70
Revises: de127679abc1
Create Date: 2024-04-21 01:27:44.109934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52338fcc6a70'
down_revision = 'de127679abc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=225), nullable=True),
    sa.Column('note', sa.String(length=10000), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###
